/*\
title: $:/plugins/tobibeer/make/filters.js
type: application/javascript
module-type: filteroperator

a filter to generate tiddler titles

@preserve
\*/
(function(){"use strict";exports.make=function(e,t,i){var r,a,n,d,u,c,l,p,s=[],m=i.widget,f=i.wiki,o=[],x={inc:1,min:1,sep:" ",tiddler:m?m.getVariable("currentTiddler"):""},g=/\%TITLE\%/gim,h=/\%COUNT\%/gim,w=/\%DATE\%/gim,D=/\%UUID\%/gim,k=/\%MAX\%/gim,T=/RANDOM\((\d*)\)/gim,$=/\%TIDDLER\%/gim,b=/^\s*([\$\w\d\-\_\/]*):(.*)(?:\s*)$/,q=function(e,t){t=t||16;var i="",r=function(){var e=Math.floor(Math.random()*62);return e<10?e:e<36?String.fromCharCode(e+55):String.fromCharCode(e+61)};while(t--){i+=r()}return i},N=function(e,t){return f.getTextReference(t,"",x.tiddler)},v=function(e,t){return m?m.getVariable(t):""},C=function(e){return e.replace(/{{([^}]*)}}/gm,N).replace(/<<([^>]*)>>/gm,v)},E=function(e,t){var i,r=x.pad&&x.expr.indexOf("%count%")<0?x.pad:0,a=f.getTiddler(x.tiddler),n=x.uniq===1?f.getTiddlerData(x.tiddler,{}):0,d=r?0:-1;do{d++;i=t+(d>0?x.sep+(r?$tw.utils.pad(d,r):d):"")}while(e.indexOf(i)>=0||x.uniq===undefined&&f.tiddlerExists(i)||x.uniq===0&&a.hasField(i)||x.uniq===1&&$tw.utils.hop(n,i));return i};e(function(e,t){s.push(t)});d=!(s.length===1&&!s[0]);try{$tw.utils.each((t.operand||"").split("\\"),function(e){var t;e=e.trim();if(e){u=b.exec(e);if(u){switch(u[1]){case"min":case"max":case"inc":t=parseInt(C(u[2]));if(isNaN(t)||t<1){t=1}x[u[1]]=t;break;case"sep":x.sep=u[2];break;case"unique":x.uniq=u[2]==="field"?0:1;break;case"pad":x.pad=parseInt(u[2]);break;case"tiddler":x.tiddler=u[2];break;case"date-format":x.dateFormat=u[2].trim();break}}else if(x.expr===undefined){x.expr=e}}});if(x.uniq===0){x.sep=x.sep===" "?"":x.sep.trim()}if(x.expr===undefined){x.expr="%tiddler%"}if(x.pad!==undefined&&isNaN(x.pad)){x.pad=x.max?x.max.toString().length:2}if(d){x.max=x.max?Math.min(s.length,x.max):s.length}if(!x.max||x.max<x.min){x.max=x.min}l=new Date;n=l;x.count=x.min;c=T.test(x.expr);if(w.test(x.expr)){r=x.dateFormat?$tw.utils.formatDateString(l,x.dateFormat):$tw.utils.stringifyDate(l)}p=D.test(x.expr);do{a=C(x.expr);if(c){a=a.replace(T,q)}if(p){a=a.replace(D,$tw.utils.uuid())}a=E(o,a.replace($,x.tiddler).replace(g,d?s[x.count-1]:x.tiddler).replace(k,x.max).replace(h,x.pad?$tw.utils.pad(x.count,x.pad):x.count).replace(w,r));o.push(a);x.count=x.count+x.inc;if(x.count%500===0){n=new Date}}while(x.count<=x.max&&n-l<5e3)}catch(I){return["Error in make filter:\n"+I]}return o}})();