/*\
title: $:/plugins/tobibeer/make/filters.js
type: application/javascript
module-type: filteroperator

a filter to generate tiddler titles

@preserve
\*/
(function(){"use strict";exports.make=function(e,t,i){var r,n,a,d,u,c,l,s,m=[],o=i.widget,f=i.wiki,p=[],g={inc:1,min:1,sep:" ",tiddler:o?o.getVariable("currentTiddler"):""},x=/\%TITLE\%/gim,h=/\%COUNT\%/gim,w=/\%DATE\%/gim,D=/\%UUID\%/gim,T=/\%MAX\%/gim,k=/RANDOM\((\d*)\)/gim,b=/\%TIDDLER\%/gim,q=/^\s*([\$\w\d\-\_\/]*):(.*)(?:\s*)$/,$=function(e,t){t=t||16;var i="",r=function(){var e=Math.floor(Math.random()*62);return e<10?e:e<36?String.fromCharCode(e+55):String.fromCharCode(e+61)};while(t--){i+=r()}return i},v=function(e,t){return f.getTextReference(t,"",g.tiddler)},C=function(e,t){return o?o.getVariable(t):""},E=function(e){return e.replace(/{{([^}]*)}}/gm,v).replace(/<<([^>]*)>>/gm,C)},M=function(e,t){var i=0,r=t,n=f.getTiddler(g.tiddler),a=g.uniq===1?f.getTiddlerData(g.tiddler,{}):0;while(e.indexOf(r)>=0||!g.uniq&&f.tiddlerExists(r)||g.uniq===0&&n.hasField(r)||g.uniq===1&&$tw.utils.hop(a,r)){i++;r=t+g.sep+i.toString()}return r};e(function(e,t){m.push(t)});d=!(m.length===1&&!m[0]);try{$tw.utils.each((t.operand||"").split("\\"),function(e){var t;e=e.trim();if(e){u=q.exec(e);if(u){switch(u[1]){case"min":case"max":case"inc":t=parseInt(E(u[2]));if(isNaN(t)||t<1){t=1}g[u[1]]=t;break;case"sep":g.sep=u[2];break;case"unique":g.uniq=u[2]==="field"?0:1;break;case"tiddler":g.tiddler=u[2];break;case"date-format":g.dateFormat=u[2].trim();break}}else if(g.expr===undefined){g.expr=e}}});if(g.uniq===0){g.sep=g.sep===" "?"":g.sep.trim()}if(g.expr===undefined){g.expr="%tiddler%"}if(d){g.max=g.max?Math.min(m.length,g.max):m.length}if(!g.max||g.max<g.min){g.max=g.min}l=new Date;a=l;g.count=g.min;c=k.test(g.expr);if(w.test(g.expr)){r=g.dateFormat?$tw.utils.formatDateString(l,g.dateFormat):$tw.utils.stringifyDate(l)}s=D.test(g.expr);do{n=E(g.expr);if(c){n=n.replace(k,$)}if(s){n=n.replace(D,$tw.utils.uuid())}n=M(p,n.replace(b,g.tiddler).replace(x,d?m[g.count-1]:g.tiddler).replace(T,g.max).replace(h,g.count).replace(w,r));p.push(n);g.count=g.count+g.inc;if(g.count%500===0){a=new Date}}while(g.count<=g.max&&a-l<5e3)}catch(F){return["Error in make filter:\n"+F]}return p}})();